events {
    worker_connections 1024;
}

pid logs/sitio3.pid;

http {
    server {
        listen 83;
        server_name localhost;

        location / {
            root /mnt/c/Users/gabo3/desWeb/17289/nginx/3sitios/sitio3;
            index index.html;
        }
    }
}
