events {
    worker_connections 1024;
}

pid logs/sitio1.pid;

http {
    server {
        listen 81;
        server_name localhost;

        location / {
            root /mnt/c/Users/gabo3/desWeb/17289/nginx/3sitios/sitio1;
            index index.html;
        }
    }
}
